// Generated by scripts/generate-home-updates.mjs. Regenerate rather than editing.
const freeze = (value) => {
  if (value && typeof value === 'object') {
    Object.values(value).forEach(freeze);
    Object.freeze(value);
  }
  return value;
};
export const homeUpdatesContent = freeze(JSON.parse('{"schema":1,"version":"4.0.1","previousVersion":"4.0.0","sourceMode":"candidate","catalogs":{"target":"7f7dfbd74686b4294498a715362a2ea1f7eb1f7328c31037698ae395c7377589","previous":"7f7dfbd74686b4294498a715362a2ea1f7eb1f7328c31037698ae395c7377589"},"digest":"50211c8ebcede05cd10ab981a6243236091676130532d115225b9e8020d3e4b0","batch":{"id":40000000002,"features":["Use an Android More button with the required larger touch target."],"listIds":[]}}'));
