// Generated by scripts/generate-home-updates.mjs. Regenerate rather than editing.
const freeze = (value) => {
  if (value && typeof value === 'object') {
    Object.values(value).forEach(freeze);
    Object.freeze(value);
  }
  return value;
};
export const homeUpdatesContent = freeze(JSON.parse('{"schema":1,"version":"3.2.0","previousVersion":"3.1.0","sourceMode":"candidate","catalogs":{"target":"959d24c5984cf3a06a00d18d8a3c0c587763c243ba6c51b7fa2715ed0e60eeed","previous":"f2615371aa864e5fb8c85fca90a116d5ef36fc995ddc86598b952daef7476ba1"},"digest":"649f7ae7b627bbe08eca28584c8930904f54f80b974f263da87109b7ea7f9feb","batch":{"id":30000200001,"features":["Build personal Reading Lists from selected issue, series and creator search results.","Choose reading alternatives from separately named cards, including the 69-issue Secret Wars fast track and a separately saved Doomsday companion.","Explore owner-selected MCU Prep guides for Fantastic Four: First Steps, Eternals, Deadpool & Wolverine, Daredevil, Moon Knight, Thunderbolts* and Shang-Chi.","Finish and reopen Reading Lists without deleting them, keep optional thumbs private, and find verified related next reads.","Open quiet What\'s new highlights on Home to see included improvements and new Reading Lists.","Keep Read and Done, next together, with secondary choices disclosed and simpler phone navigation."],"listIds":["mcu-prep-shang-chi-and-the-legend-of-the-ten-rings","mcu-prep-thunderbolts","mcu-prep-moon-knight","mcu-prep-eternals","mcu-prep-fantastic-four-first-steps","mcu-prep-deadpool-and-wolverine","avengers-doomsday-secret-wars","mcu-prep-daredevil-born-again"]}}'));
