// Generated by scripts/generate-home-updates.mjs. Regenerate rather than editing.
const freeze = (value) => {
  if (value && typeof value === 'object') {
    Object.values(value).forEach(freeze);
    Object.freeze(value);
  }
  return value;
};
export const homeUpdatesContent = freeze(JSON.parse('{"schema":1,"version":"4.0.0","previousVersion":"3.2.0","sourceMode":"candidate","catalogs":{"target":"7f7dfbd74686b4294498a715362a2ea1f7eb1f7328c31037698ae395c7377589","previous":"959d24c5984cf3a06a00d18d8a3c0c587763c243ba6c51b7fa2715ed0e60eeed"},"digest":"0916df3fbae66946b92df011b756d3fd60c997400f96227b17b541217ba11e11","batch":{"id":40000000001,"features":["Rate individual comics privately from half a star to five stars without marking them read.","Browse MCU Prep by movie or series release, switch between oldest and newest, and search by title or character.","Find new MCU Prep guides for Spider-Man: Brand New Day, She-Hulk, Ms. Marvel, Captain America: Brave New World, Guardians of the Galaxy and Agatha All Along.","Read with clearer Read and Done actions, compact list controls and easier navigation on phones and long Reading Lists.","Keep unfinished pasted orders on your device and resume matching without losing their source or unresolved positions.","Choose clearly named backups for reading data, completion history and unfinished imports, with recovery messages that explain what was actually saved or retained."],"listIds":["mcu-prep-spider-man-brand-new-day","mcu-prep-she-hulk","mcu-prep-ms-marvel","mcu-prep-captain-america-brave-new-world","mcu-prep-guardians-of-the-galaxy","mcu-prep-agatha-all-along"]}}'));
